---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-pull-secret-patcher

resources:
  - ../../base
  - ./resources/rbac.yaml
  - ./resources/deployment.yaml

generators:
  - ./generators/secrets-generator.yaml
