---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - ../../base
  - ./resources/serviceaccount.yaml
  - ./resources/clusterrole.yaml
  - ./resources/clusterrolebinding.yaml
  - ./resources/gatewayclass.yaml
  - ./resources/gateway.yaml
  - ./resources/service.yaml
  - ./resources/daemonset.yaml
