---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: longhorn-vsvc
  namespace: longhorn-system
spec:
  hosts:
    - longhorn.k3s.effectful.co
  http:
    - route:
        - destination:
            host: longhorn-frontend
  gateways:
    - istio-system/k3s-effectful-co-internal
