---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      # - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      # - id: check-yaml
      #   args: [--allow-multiple-documents]
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.77.1
    hooks:
      - id: terraform_fmt

  # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.git
  #   rev: 0.2.2
  #   hooks:
  #     - id: yamlfmt
  #       args:
  #         - --mapping
  #         - '2'
  #         - --sequence
  #         - '4'
  #         - --offset
  #         - '2'
  #         - --explicit_start
