---
keys:
  # Personal
  - &admin_maxwellbrown age1usc2072gec0plj2q866m0uyeh2rly60xnxts4c3xxh50cwygte8s8avj8a
  - &admin_mikearnaldi age15umcap7zkzq5g32zykcywjk0l6cwldxqk7e46t2ynkkwy0eghuas5rs6t7
  # Hosts
  - &host_devbox age1cd8stpd83v0zwfk7ke80nag65mxvxgc8rfjx86a4rk35wevymfwq747zwx
  # K3s
  - &k3s_sops_operator age1pwu309yva6z9qs5z4n5dytns3jze850das6y2qntqq5yc8wzc52sk4nufy
creation_rules:
  - encrypted_regex: ^(data|stringData)$
    path_regex: k3s/.*/secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *admin_maxwellbrown
          - *admin_mikearnaldi
          - *k3s_sops_operator
  - path_regex: nixos/.*/secrets\.ya?ml$
    key_groups:
      - age:
          - *admin_maxwellbrown
          - *admin_mikearnaldi
          - *host_devbox
  - path_regex: terraform/.*/secrets\.ya?ml$
    key_groups:
      - age:
          - *admin_maxwellbrown
          - *admin_mikearnaldi
