[tool.ruff]
target-version = "py310"
line-length = 88
select = [
  "E", # pycodestyle
  "W", # pycodestyle
  "F", # Pyflakes
  "UP", # pyupgrade
  "N", # pep8-naming
  "YTT", # flake8-2020
  "S", # flake8-bandit
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "T10", # flake8-debugger
  "ISC", # flake8-implicit-str-concat
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "DTZ", # flake8-datetimez
  "I", # isort
  "PGH", # pygrep-hooks
  "PLC", # Pylint
  "PIE", # flake8-pie
  "RUF" # ruff
]
ignore = [
  "E501" # leave line length enforcement to black
]

[tool.ruff.isort]
lines-between-types = 1
lines-after-imports = 2

[tool.mypy]
python_version = "3.10"
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "setuptools.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true
