# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{modulesPath, ...}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    binfmt = {
      emulatedSystems = ["x86_64-linux"];
    };

    cleanTmpDir = true;

    kernel = {
      sysctl = {
        "net.ipv4.ip_forward" = true;
        "net.ipv6.conf.all.forwarding" = true;
      };
    };

    kernelParams = [
      "console=ttyS0"
      "console=tty1"
      "nvme.shutdown_timeout=10"
      "libiscsi.debug_libiscsi_eh=1"
    ];

    loader = {
      efi = {
        canTouchEfiVariables = true;
      };

      systemd-boot = {
        enable = true;
      };
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/56f99580-5fe1-4985-8324-a3153f0894bb";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/0E9E-27BC";
      fsType = "vfat";
    };
  };

  swapDevices = [];
}
