---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: actions-runner-system

resources:
  - ../../base
  - ./resources/runnerset.yaml

generators:
  - ./generators/secrets-generator.yaml
