apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  components:
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 5
          minReplicas: 2
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
      - name: istio-external
        enabled: true
        label:
          istio: istio-external
        k8s:
          hpaSpec:
            minReplicas: 2
            maxReplicas: 5
          service:
            type: NodePort
      - name: knative
        enabled: true
        label:
          istio: knative
        k8s:
          hpaSpec:
            minReplicas: 2
            maxReplicas: 5
          service:
            type: ClusterIP
      - name: istio-internal
        enabled: true
        label:
          istio: istio-internal
        k8s:
          hpaSpec:
            minReplicas: 2
            maxReplicas: 5
          service:
            type: ClusterIP
