---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: image-pull-secret
data:
  .dockerconfigjson: ENC[AES256_GCM,data:N7U8Bo2ANASGRIgT2I8KcPtQPOyePTm2esJOqrdcv8NRGP69QMxQaBz7Vbwwy6+bBbycCy3YDaW7YdiXhw2n7uGf26FWskqKZr5JKzbZRC36W2w1iTas5zHIiPA/u4c9Mg8+QIiO5K7n2NnL4ihsspDvfZ++l1BovWWUwJAlfSjPd/7OwJq4FdsPPeGLfoLvMbaT/WHZSzgUDgfBER79eRzC1QaU7BBCANdyjzF5LxQpTI+lKoaigEDj3i70UR6BUIC2dalWEh28LRROuqNHpoKAQDhK+Q3EpA/8o2PzOR1weXqFnTeMQKxHA8XjdS8WT4jzsCz8NCGs/2JnBCedBDS7wNWbPneun/crt+isFPeEXMPlxJ6lTOOIYJQsEko2nv9xcQ==,iv:1/YpDUy+96AXTc77PAmwiw7TZZFa0svE+Ea99fxRjQQ=,tag:xB98hi8QbtoFVYlHLsqj1A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1usc2072gec0plj2q866m0uyeh2rly60xnxts4c3xxh50cwygte8s8avj8a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUExDNmZadk1yeVdmQzV3
        a0NXbVJjcFdUa2FXYXNUdG1FeVVaRnZoa1hzCmYvMGhETEllQkNrdG04Sk5HYlZJ
        RTAyYkFpQlRDL0V1YUZFczJxL0NUYTgKLS0tIGFOQXA2Tk9HN0p0UlNhUzROVFZj
        ZFBrdG8zU09tRDQ2UVRBMHNJWnh0bzAKrgUVQmN4B7fcn6MnTRYeQoQ80bjwJOOb
        QXiuIV1/8BPZxIexKXKhsBhxIkqV9eLRh9VXG3kWUG9f+pBoDmgAWg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age15umcap7zkzq5g32zykcywjk0l6cwldxqk7e46t2ynkkwy0eghuas5rs6t7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQVRJdnVEMy9GdG1pTEdV
        OVNjRVYvZE1hWEcwRE9NQkdkeHZmN1RUZUJvCjRmbG55NFhVcVdqV09WWUVVREtD
        OE9GdzJ3WjJlMXhHVTI5QVJEOWxoQVUKLS0tIHZFSm9ZczlzeUEzVzdKNmNscGtN
        MStySFF1emFzcnVIUFVWVGV4S0NFaWsK4+vEqOd6uV0hXRRsyJIsGsxOT3CJNieg
        7DtkVa5cPSsDLyQsRxqNSaPHb8PLz4FEmmTrb4k2HGP9rikYtsBmQQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pwu309yva6z9qs5z4n5dytns3jze850das6y2qntqq5yc8wzc52sk4nufy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZExnRzJHSm1DRTBqVGZI
        V0hzNnp5YUpaR25KQi9CSzRqNDNJSmI5dVhrCmh3NDF5MHhvL01KaEVnbmlzQ2hs
        OWE4ZnArT0ZiNndqQkhGM3hLdFBEOWcKLS0tIGZOdC83c1FqMDVFZWFsZHRtT0xs
        ZXpZWlhTNVpFRXZzb013UHBuL1ZWNEkK5v7+sLuBNF72lmxWiMQzEtL3eNCtam9B
        A3tcsIBp5i7HO2HwezUNvnIMkCuNQq22mptD5MUfxKVjmL4NtUYk0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-04-08T03:36:23Z'
  mac: ENC[AES256_GCM,data:g7E+fJdBIUCUyMRpP+54WsuchIAEiHSmYcMsu27BQxJs2l8NA4FMf2d9k+HvTxCI9P6dEumjy8O/JNXN428l9DgarHOCi6EToINde4gxJYhP++nlgDoW8nHfy1YXl9E7Ic3cBWDa+xjfLYy9aKn9uYMvHEySXN3zRBWtXP44RcM=,iv:Bif2ceZ3+3bahePDNWx9s2D/5RMhwrG++AOJOpFUOc8=,tag:amBZN2WB1xCq0HxjYWreIA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
