---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-pull-secret-patcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-pull-secret-patcher
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - list
      - patch
      - create
      - get
      - delete
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-pull-secret-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-pull-secret-patcher
subjects:
  - kind: ServiceAccount
    name: image-pull-secret-patcher
