---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-administrator
subjects:
  - kind: User
    name: maxwellbrown
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: mikearnaldi
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
...
