---
name: Pull Request CI

on:
  pull_request:
    branches:
      - main

  # Allows for running this workflow manually from the GitHub Actions UI
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            keep-outputs = true
            keep-derivations = true
      - name: Cache nix
        uses: cachix/cachix-action@v12
        with:
          name: effect-ts
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Setup direnv
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.2
      - run: nix flake check --show-trace
